steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg=VITE_FIREBASE_API_KEY=${_FIREBASE_API_KEY}'
      - '--build-arg=VITE_FIREBASE_AUTH_DOMAIN=${_FIREBASE_AUTH_DOMAIN}'
      - '--build-arg=VITE_FIREBASE_PROJECT_ID=$PROJECT_ID'
      - '-t'
      - '${_IMAGE_REPOSITORY}/meal-planner:$SHORT_SHA'
      - '-t'
      - '${_IMAGE_REPOSITORY}/meal-planner:latest'
      - '-f'
      - 'Dockerfile'
      - '.'
    timeout: 600s

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE_REPOSITORY}/meal-planner:$SHORT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE_REPOSITORY}/meal-planner:latest']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'meal-planner'
      - '--image=${_IMAGE_REPOSITORY}/meal-planner:$SHORT_SHA'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--port=8080'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--max-instances=2'
      - '--timeout=60s'
      - '--set-env-vars=REPO_TYPE=firestore,ALLOWED_DOMAIN=tarttelin.co.uk,API_KEY=${_API_KEY},FIT_FILES_BUCKET=${_FIT_FILES_BUCKET},STRAVA_CLIENT_ID=${_STRAVA_CLIENT_ID},STRAVA_CLIENT_SECRET=${_STRAVA_CLIENT_SECRET}'
      - '--allow-unauthenticated'

options:
  machineType: 'E2_MEDIUM'
  substitutionOption: 'ALLOW_LOOSE'
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: 'europe-west1'
  _FIREBASE_API_KEY: ''
  _FIREBASE_AUTH_DOMAIN: 'tartties-meals.firebaseapp.com'
  _IMAGE_REPOSITORY: 'europe-west1-docker.pkg.dev/tartties-meals/meal-planner'
  _API_KEY: ''
  _FIT_FILES_BUCKET: 'tartties-meals-shopping-fit-files'
  _STRAVA_CLIENT_ID: ''
  _STRAVA_CLIENT_SECRET: ''

images:
  - '${_IMAGE_REPOSITORY}/meal-planner:$SHORT_SHA'
  - '${_IMAGE_REPOSITORY}/meal-planner:latest'

timeout: 1200s
